<a href="https://colab.research.google.com/github/pratikshas8080/Python_Basics-/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [3]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np

print(np.__version__)

1.18.5


In [7]:
import numpy as np

print(np.__version__)

1.18.5


In [8]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [9]:
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array
import numpy as np

arr = np.array(42)

print(arr)

42


In [10]:
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [11]:
#An array that has 1-D arrays as its elements is called a 2-D array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
#An array that has 2-D arrays (matrices) as its elements is called 3-D array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
#When the array is created, you can define the number of dimensions by using the ndmin argument.
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [16]:
#The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2
