<a href="https://colab.research.google.com/github/pratikshas8080/Python_Basics-/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy

In [ ]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np

print(np.__version__)

1.18.5


In [ ]:
import numpy as np

print(np.__version__)

1.18.5


In [ ]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [ ]:
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array
import numpy as np

arr = np.array(42)

print(arr)

42


In [ ]:
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
#An array that has 1-D arrays as its elements is called a 2-D array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#An array that has 2-D arrays (matrices) as its elements is called 3-D array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#When the array is created, you can define the number of dimensions by using the ndmin argument.
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
#The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [ ]:
#Get third and fourth elements from the following array and add them
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
#To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [ ]:
#To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
#The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
#access 2D array 
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [ ]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[0,1,2])

6


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [ ]:
#Slicing in python means taking elements from one given index to another given index
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [ ]:
#negative slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
#The NumPy array object has a property called dtype that returns the data type of the array
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
#Get the data type of an array containing strings
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
#We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#Create an array with data type 4 bytes integer
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
#The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
#The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
#The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
#Change data type from float to integer by using int as parameter value
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
#The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
#The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
#The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#Make a view, change the original array, and display both arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#Make a view, change the view, and display both arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)
#Copy As View End

None
[1 2 3 4 5]


In [ ]:
#NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
#You are allowed to have one "unknown" dimension.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Flattening array means converting a multidimensional array into a 1D array.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
#Iterating means going through elements one by one.
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
#Iterate on the elements of the following 2-D array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
#Iterate on each scalar element of the 2-D array:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
#Iterate on the elements of the following 3-D array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
#Iterate down to the scalars
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
#Iterate through the array as a string
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [ ]:
#Iterate through every scalar element of the 2D array skipping 1 element
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
#Enumerate on following 1D arrays elements
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
#Enumerate on following 2D array's elements
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
#We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#NumPy provides a helper function: hstack() to stack along rows
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
#NumPy provides a helper function: vstack()  to stack along columns
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
#We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#Split the array in 4 parts
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
#The return value of the array_split() method is an array containing each of the split as an array
#Access the splitted arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
#Use the array_split() method, pass in the array you want to split and the number of splits you want to do
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#Split the 2-D array into three 2-D arrays
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#To search an array, use the where() method
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
#Find the indexes where the values are even
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
#Find the indexes where the values are odd
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [ ]:
#There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [ ]:
#By default the left most index is returned, but we can give side='right' to return the right most index instead
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [ ]:
#To search for more than one value, use an array with the specified values
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [ ]:
#The NumPy ndarray object has a function called sort(), that will sort a specified array
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
#Sort the array alphabetically:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
#Sort a boolean array
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [ ]:
#If you use the sort() method on a 2-D array, both arrays will be sorted
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
#If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [ ]:
#In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
#Create a filter array that will return only values higher than 42
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
#Create a filter array that will return only even elements from the original array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
#The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
#Create a filter array that will return only even elements from the original array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [ ]:
#NumPy offers the random module to work with random numbers
from numpy import random

x = random.randint(100)

print(x)

76


In [ ]:
#Without ufunc, we can use Python's built-in zip() method
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)


[5, 7, 9, 11]


In [ ]:
#With ufunc, we can use the add() function
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


The frompyfunc() method takes the following arguments:

1. function - the name of the function.
2. inputs - the number of input arguments (arrays).
3. outputs - the number of output arrays. 

In [ ]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [ ]:
#A ufunc should return <class 'numpy.ufunc'>
import numpy as np

print(type(np.add))

<class 'numpy.ufunc'>


In [ ]:
#Check the type of another function: concatenate()
import numpy as np

print(type(np.concatenate))

<class 'function'>


In [ ]:
#Use an if statement to check if the function is a ufunc or not
import numpy as np

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


In [ ]:
#The add() function sums the content of two arrays, and return the results in a new array.
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [ ]:
#The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [ ]:
#The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [ ]:
#The divide() function divides the values from one array with the values from another array, and return the results in a new array.
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [ ]:
#The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [ ]:
#Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [ ]:
#You get the same result when using the remainder() function
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [ ]:
#The divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [ ]:
#Both the absolute() and the abs() functions functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


There are primarily five ways of rounding off decimals in NumPy:

1.truncation
2.fix
3.rounding
4.floor
5.ceil

In [ ]:
#Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [ ]:
import numpy as np

arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [ ]:
#The around() function increments preceding digit or decimal by 1 if >=5 else do nothing
import numpy as np

arr = np.around(3.1666, 2)

print(arr)

3.17


In [ ]:
#The floor() function rounds off decimal to nearest lower integer
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [ ]:
#The ceil() function rounds off decimal to nearest upper integer
import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [ ]:
#Use the log2() function to perform log at the base 2
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
#Use the log10() function to perform log at the base 10
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [ ]:
#Use the log() function to perform log at the base e
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [ ]:
#NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


In [ ]:
#Add the values in arr1 to the values in arr2
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [ ]:
#Sum the values in arr1 and the values in arr2
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [ ]:
#If you specify axis=1, NumPy will sum the numbers in each array
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [ ]:
#Perform cummulative summation in the following array
import numpy as np

arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


In [1]:
#To find the product of the elements in an array, use the prod() function
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [2]:
#Find the product of the elements of two arrays
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [3]:
#If you specify axis=1, NumPy will return the product of each array.
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [4]:
#Cummulative product means taking the product partially
import numpy as np

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


In [5]:
#Compute discrete difference of the following array
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [6]:
#The Lowest Common Multiple is the least number that is common multiple of both of the numbers
import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [7]:
#The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension
import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [8]:
#Find the LCM of all of an array where the array contains all integers from 1 to 10
import numpy as np

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


In [9]:
#The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [10]:
#The reduce() method will use the ufunc, in this case the gcd() function, on each element, and reduce the array by one dimension.
import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


In [11]:
#NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


In [12]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [13]:
#By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumP.
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [14]:
#Convert all of the values in following array arr to degrees
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [15]:
#NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [16]:
#Find the angle for all of the sine values in the array
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [17]:
#NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


In [18]:
#NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values
import numpy as np

x = np.sinh(np.pi/2)

print(x)

2.3012989023072947


In [19]:
#Find cosh values for all of the values in arr
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [20]:
#Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.
import numpy as np

x = np.arcsinh(1.0)

print(x)

0.881373587019543


In [21]:
#Find the angle for all of the tanh values in array
import numpy as np

arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

[0.10033535 0.20273255 0.54930614]


In [22]:
#A set in mathematics is a collection of unique elements
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [23]:
#To find the unique values of two arrays, use the union1d() method
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [24]:
#To find only the values that are present in both arrays, use the intersect1d() method
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [25]:
#To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [26]:
#To find only the values that are NOT present in BOTH sets, use the setxor1d() method
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
