<a href="https://colab.research.google.com/github/pratikshas8080/Python_Basics-/blob/master/Random_no_in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#NumPy offers the random module to work with random numbers.
from numpy import random

x = random.randint(100)

print(x)

78


In [2]:
#The random module's rand() method returns a random float between 0 and 1
from numpy import random

x = random.rand()

print(x)

0.10993684956537031


In [3]:
#The randint() method takes a size parameter where you can specify the shape of an array
from numpy import random

x=random.randint(100, size=(5))

print(x)

[91 86  2 43 83]


In [4]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[29 51 17 10  9]
 [63 24 23  3 51]
 [27 45 56  1 71]]


In [5]:
#The rand() method also allows you to specify the shape of the array
from numpy import random

x = random.rand(5)

print(x)

[0.56766422 0.33657475 0.83751014 0.99619079 0.83495515]


In [6]:
#Generate a 2-D array with 3 rows, each row containing 5 random numbers
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.06418668 0.36556275 0.50285412 0.15051513 0.15531442]
 [0.179704   0.26012143 0.71859525 0.34865825 0.74846709]
 [0.61853732 0.8596352  0.2296059  0.20237459 0.07915406]]


In [7]:
#The choice() method takes an array as a parameter and randomly returns one of the values.
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

7


In [8]:
#The choice() method also allows you to return an array of values
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 9 5 7 3]
 [9 5 5 5 9]
 [7 7 9 5 7]]


In [9]:
#Data Distribution is a list of all possible values, and how often each value occurs.
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[5 5 5 3 7 7 7 7 7 7 5 7 5 3 7 5 7 5 5 7 7 7 5 7 5 5 5 5 7 7 5 7 7 7 7 5 7
 7 7 7 7 7 5 5 7 5 7 7 7 7 3 7 7 7 7 7 5 7 7 5 5 7 7 7 7 7 7 7 7 7 5 7 7 7
 7 7 7 3 5 5 5 7 5 7 5 5 7 5 7 7 5 3 7 7 7 7 3 3 5 3]


In [10]:
#The NumPy Random module provides two methods for this: shuffle() and permutation()
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[2 4 3 1 5]


In [11]:
#Generate a random permutation of elements of following array
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[5 3 4 2 1]
